apiVersion: management.loft.sh/v1
kind: ArgoCDApplication
metadata:
  name: {{ include "slinky.namePrefix" . }}-cert-manager
  namespace: {{ .Values.loft.space }}
  annotations:
    argocd.argoproj.io/sync-wave: "-30"
spec:
  destination:
    virtualCluster:
      name: {{ .Values.loft.virtualClusterName }}
      target: vCluster
      namespace: {{ .Values.certManager.namespace }}
  template:
    spec:
      project: {{ .Values.argoCDProject }}
      source:
        repoURL: https://charts.jetstack.io
        chart: cert-manager
        targetRevision: {{ .Values.certManager.version }}
        helm:
          releaseName: cert-manager
          valuesObject:
            crds:
              enabled: true
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
