apiVersion: management.loft.sh/v1
kind: ArgoCDApplication
metadata:
  name: {{ include "slinky.namePrefix" . }}-slurm-operator
  namespace: {{ include "slinky.projectNamespace" . }}
  labels:
    loft.sh/argocd-application-id: slurm-operator
    {{- include "slinky.commonLabels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "-20"
    loft.sh/argocd-connector: {{ .Values.loft.connector }}
spec:
  displayName: slurm-operator
  destination:
    virtualCluster:
      name: {{ .Values.loft.virtualClusterName }}
      target: vCluster
      namespace: {{ .Values.slinkyOperator.namespace }}
  template:
    spec:
      project: {{ .Values.argoCDProject }}
      source:
        repoURL: ghcr.io/slinkyproject/charts
        chart: slurm-operator
        targetRevision: {{ .Values.slinkyOperator.version }}
        helm:
          releaseName: slurm-operator
          valuesObject:
            crds:
              enabled: true
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
