apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ include "slinky.namePrefix" . }}-slurm-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-20"
spec:
  project: {{ .Values.argoCDProject }}
  destination:
    name: {{ include "slinky.destClusterName" . }}
    namespace: {{ .Values.slinkyOperator.namespace }}
  source:
    repoURL: ghcr.io/slinkyproject/charts
    chart: slurm-operator
    targetRevision: {{ .Values.slinkyOperator.version }}
    helm:
      releaseName: slurm-operator
      valuesObject:
        crds:
          enabled: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
