apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: slinky-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-20"
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: slinky
  source:
    repoURL: ghcr.io/slinkyproject/charts
    chart: slurm-operator
    targetRevision: 1.1.0
    helm:
      releaseName: slurm-operator
      valuesObject:
        crds:
          enabled: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
